{"uuid": "c09d709f-9df3-485b-83f1-3bb57b2c5f22", "children": ["ac226585-b6d8-4005-a815-f25cf3a3f4c0", "3763bda8-cf72-4ec6-b88d-8d508eac43a7", "f4cf9b5a-789f-42c6-91db-c3cd20050c28", "ea646dac-e34d-4cb7-a9e9-de848f1d2cda", "c3bf3d6b-36d5-4a4c-89d1-f71a29eaa1e1"], "befores": [{"name": "login_fixture", "status": "broken", "statusDetails": {"message": "AttributeError: 'Response' object has no attribute 'response'\n", "trace": "  File \"/Users/mac/Documents/GitHub/pytestDemo/.venv/lib/python3.9/site-packages/pluggy/callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/mac/Documents/GitHub/pytestDemo/.venv/lib/python3.9/site-packages/_pytest/fixtures.py\", line 937, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/mac/Documents/GitHub/pytestDemo/.venv/lib/python3.9/site-packages/_pytest/fixtures.py\", line 790, in call_fixture_func\n    res = next(it)\n  File \"/Users/mac/Documents/GitHub/pytestDemo/testcases/conftest.py\", line 57, in login_fixture\n    yield loginInfo.response.json()\n"}, "steps": [{"name": "前置步骤 ==>> 管理员用户登录", "status": "passed", "parameters": [{"name": "username", "value": "'wintest'"}, {"name": "password", "value": "'123456'"}], "start": 1744990584232, "stop": 1744990584233}], "start": 1744990584148, "stop": 1744990584233}], "start": 1744990584148, "stop": 1744990586374}