{"name": "用户注册登录查看-预期成功", "status": "failed", "statusDetails": {"message": "AssertionError: 接口返回码是 【 2005 】, 返回信息：手机号已被注册！！！ \nassert False is True\n +  where False = <core.result_base.ResultBase object at 0x1040dea60>.success", "trace": "self = <testcases.scenario_test.test_01_register_login_list.TestRegLogList object at 0x10412d250>\ntestcase_data = {'address': '深圳市宝安区', 'except_code': 0, 'except_msg': '查询成功', 'except_result': True, ...}\n\n    @allure.story(\"用例--注册/登录/查看--预期成功\")\n    @allure.description(\"该用例是针对 注册-登录-查看 场景的测试\")\n    @allure.issue(\"https://blog.csdn.net/\", name=\"点击，跳转到对应BUG的链接地址\")\n    @allure.testcase(\"https://blog.csdn.net/\", name=\"点击，跳转到对应用例的链接地址\")\n    @allure.title(\"用户注册登录查看-预期成功\")\n    @pytest.mark.multiple\n    @pytest.mark.usefixtures(\"delete_register_user\")\n    def test_user_register_login_list(self, testcase_data):\n        username = testcase_data[\"username\"]\n        password = testcase_data[\"password\"]\n        telephone = testcase_data[\"telephone\"]\n        sex = testcase_data[\"sex\"]\n        address = testcase_data[\"address\"]\n        except_result = testcase_data[\"except_result\"]\n        except_code = testcase_data[\"except_code\"]\n        except_msg = testcase_data[\"except_msg\"]\n        logger.info(\"*************** 开始执行用例 ***************\")\n        result = register_user(username, password, telephone, sex, address)\n        step_1(username, password, telephone, sex, address)\n>       assert result.success is True, result.error\nE       AssertionError: 接口返回码是 【 2005 】, 返回信息：手机号已被注册！！！ \nE       assert False is True\nE        +  where False = <core.result_base.ResultBase object at 0x1040dea60>.success\n\ntestcases/scenario_test/test_01_register_login_list.py:46: AssertionError"}, "description": "该用例是针对 注册-登录-查看 场景的测试", "steps": [{"name": "步骤1 ==>> 注册用户", "status": "passed", "parameters": [{"name": "username", "value": "'测试test'"}, {"name": "password", "value": "'123456'"}, {"name": "telephone", "value": "'13599999999'"}, {"name": "sex", "value": "'1'"}, {"name": "address", "value": "'深圳市宝安区'"}], "start": 1744708530788, "stop": 1744708530788}], "attachments": [{"name": "log", "source": "24166648-9fcc-4fae-a73f-5da9ddac4d73-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "ed6b8789-84c0-4b6a-a88c-25e81928f470-attachment.txt", "type": "text/plain"}], "start": 1744708530717, "stop": 1744708530789, "uuid": "721d7798-f076-4fb7-8372-849c7aaf09e3", "historyId": "3fecfd1cc16a2d017110cabee550885b", "testCaseId": "7a39fbc21de5eb85f26e4e3506cf4626", "fullName": "testcases.scenario_test.test_01_register_login_list.TestRegLogList#test_user_register_login_list", "labels": [{"name": "feature", "value": "场景：用户注册-用户登录-查看用户"}, {"name": "story", "value": "用例--注册/登录/查看--预期成功"}, {"name": "severity", "value": "critical"}, {"name": "epic", "value": "针对业务场景的测试"}, {"name": "tag", "value": "multiple"}, {"name": "parentSuite", "value": "testcases.scenario_test"}, {"name": "suite", "value": "test_01_register_login_list"}, {"name": "subSuite", "value": "TestRegLogList"}, {"name": "host", "value": "192.168.10.5"}, {"name": "thread", "value": "24590-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "testcases.scenario_test.test_01_register_login_list"}], "links": [{"type": "test_case", "url": "https://blog.csdn.net/", "name": "点击，跳转到对应用例的链接地址"}, {"type": "issue", "url": "https://blog.csdn.net/", "name": "点击，跳转到对应BUG的链接地址"}]}